### ISSUE TITLE
Problem with scrollable element

### ISSUE THREAD

**Issue by denouche** [luis-kaufmann-silva/jquery-p2r#8]
Hi!

I have a problem using your plugin in the case of a scrollable element.
This problem is easily reproductible using your example for mobile:
http://codepen.io/luiskaufmannsilva/pen/cIxqe

You just need to add 4 or 5 blocs:
```html
<p class='panel-body'>
        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>  
```
in the `<section class='panel panel-default'>` block.

After that, if you scroll down and then scroll up __by touching__ (as you could do on a mobile device), it's not possible to scroll up and the refresh event is triggered.

My guess is that in the `onTouchStart` function, the test `if (this.$scroll.scrollTop() > 0) {` is always false because `this.$scroll.scrollTop()` always return 0.

For now the workaround I found in my case is to replace the test by `if ($(document).scrollTop() > 0) {` , but I'm not sure this solution is good in all cases.

How can I fix my problem ? 

Thanks in advance

**Comment by luis-kaufmann-silva** [comment]
Hi!

Recently i added a new option called "scroll". Basically you can tell the selector responsible for the "scroll" (inside or outside the root element, this element is "this.$scroll").

I will perform a change to use the root element too (root element is the pull to refresh element, in this case).

Thanks for your issue & feedback ;)

**Comment by denouche** [comment]
Thank you !!
